[package]
name = "blockoria-application"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
blockoria-domain = { path = "../blockoria-domain" }

[dev-dependencies]
tempfile = "3"
chrono = { version = "0.4", features = ["serde"] }
